### ISSUE TITLE
Multiple values for same key results in `MultipleObjectsReturned` exception (unlike Ruby version, which doesn’t mind)

### ISSUE THREAD

**Issue by andylolz** [everypolitician/everypolitician-popolo-python#6]
EveryPolitician has 2 twitter handles on file for [Dio Wang (Australian Senate)](http://everypolitician.org/australia/senate/term-table/45.html#facet=social&search=Dio+Wang). If I try to fetch these, I get:

``` python
>>> print('{name} ({id_})'.format(name=person.name, id_=person.id))
Dio Wang (2c029580-c7cf-4f76-99da-b0beb3f265f4)

>>> person.twitter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ep-thingy/env/lib/python3.4/site-packages/popolo_data/base.py", line 144, in twitter
    return self.contact_detail('twitter') or self.link('twitter')
  File "/ep-thingy/env/lib/python3.4/site-packages/popolo_data/base.py", line 75, in contact_detail
    'contact_details', 'type', contact_type, 'value')
  File "/ep-thingy/env/lib/python3.4/site-packages/popolo_data/base.py", line 63, in get_related_value
    popolo_array, info_type_key, info_type, n))
popolo_data.base.MultipleObjectsReturned: Multiple contact_details found with type: twitter; there were 2
```

If I do the same using [everypolitician-popolo](https://github.com/everypolitician/everypolitician-popolo) (the Ruby one) it looks like I get just one of the twitter handles.

Neither of these behaviours was really what I was expecting (I suppose I expected to get a list of values derived from all the person’s contact details that are of type “twitter”). Is this a bug, or have I misunderstood? Should there be at most one contact detail per type; one identifier per scheme etc?

**Comment by mhl** [comment]
Yes, the reason I made this an exception (rather than just pick one, like the Ruby version) was that I assumed it would be a data problem that should be fixed if there were mutliple contact details with type 'twitter', as Dio Wang has:

```
      "links": [
        {
          "note": "Wikipedia (en)",
          "url": "https://en.wikipedia.org/wiki/Zhenya_Wang"
        },
        {
          "note": "Wikipedia (zh)",
          "url": "https://zh.wikipedia.org/wiki/王振亞"
        },
        {
          "note": "twitter",
          "url": "https://twitter.com/SenatorZWang"
        },
        {
          "note": "twitter",
          "url": "https://twitter.com/SenatorDioWang"
        }
```

(from https://cdn.rawgit.com/everypolitician/everypolitician-data/34c3296ca85d8d73c0bd6f1abec352840fb570a5/data/Australia/Senate/ep-popolo-v1.0.json )

I'll consult with my colleagues about this...

**Comment by andylolz** [comment]
> I assumed it would be a data problem that should be fixed if there were mutliple contact details with type 'twitter'

I am beginning to think you are right! In fact in the case of Dio Wang, it looks like he updated his twitter handle from [SenatorZWang](https://twitter.com/SenatorZWang) to [SenatorDioWang](https://twitter.com/SenatorDioWang). So overwriting the old one with the new one would have been preferable in this case.

> I'll consult with my colleagues about this...

Great – thanks, @mhl.

**Comment by mhl** [comment]
To elaborate on the automatic ticket closing - I've changed this behaviour so that:
- `twitter` returns the first Twitter username found, or `None` if there are none
- `twitter_all` returns a list of all known Twitter usernames for that person (which may be an empty list if there are none)

I haven't released a new version to PyPi yet that includes this, but will do shortly.

**Comment by mhl** [comment]
@andylolz I've released the new version to PyPi now, so this is fixed in:
- `everypolitician` == 0.0.8
- `everypolitician-popolo` == 0.0.7

... so [this code](https://github.com/andylolz/ep-twitter-ids/blob/master/scraper.py#L58-L79) can be much simplified by using `twitter_all` instead if you upgrade.

**Comment by andylolz** [comment]
NICE! Thanks!

**Comment by mhl** [comment]
:) No problem.

> So presumably this means this isn’t a data problem – i.e. multiple contact_details with the same type are fine?

Yes, that's right.
